version: '3'

services:
   web:
	 build: .
	 command: sh -c "python src/profiles_project/manager.py runserver 0.0.0.0:8000"
	 volumes:
	 - .:/code
		ports:
		- "8000:8000"

#docker-compose build
#docker-compose up